/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.DocGiaDao;
import java.sql.Date;
import models.DocGia;

/**
 *
 * @author doquy
 */
public class mainFrm extends javax.swing.JFrame {

	/**
	 * Creates new form mainFrm
	 */
	private  FisrtPn firstpn;
	private  SecondPn secondpn;
	public mainFrm() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setExtendedState(this.MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jFrame1 = new javax.swing.JFrame();
      tpnMain = new javax.swing.JTabbedPane();
      jSeparator3 = new javax.swing.JSeparator();
      jPanel1 = new javax.swing.JPanel();
      btnQuanLiSach = new javax.swing.JButton();
      btnQuanLiDocGia = new javax.swing.JButton();
      btnQuanLiMuonTra = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JSeparator();
      btnTraCuu = new javax.swing.JButton();
      btnThongKe = new javax.swing.JButton();
      btnTraCuu1 = new javax.swing.JButton();
      jSeparator5 = new javax.swing.JSeparator();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jPanel3 = new javax.swing.JPanel();
      lbMaThuThu = new javax.swing.JLabel();
      lbHoTen = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jSeparator4 = new javax.swing.JSeparator();
      jSeparator2 = new javax.swing.JSeparator();

      javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
      jFrame1.getContentPane().setLayout(jFrame1Layout);
      jFrame1Layout.setHorizontalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      jFrame1Layout.setVerticalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("QUAN LY THU VIEN");

      tpnMain.setBorder(new javax.swing.border.MatteBorder(null));

      jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

      btnQuanLiSach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
      btnQuanLiSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N
      btnQuanLiSach.setText("QUAN LI SACH");
      btnQuanLiSach.setFocusable(false);
      btnQuanLiSach.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      btnQuanLiSach.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
      btnQuanLiSach.setIconTextGap(20);
      btnQuanLiSach.setVerifyInputWhenFocusTarget(false);
      btnQuanLiSach.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnQuanLiSachActionPerformed(evt);
         }
      });

      btnQuanLiDocGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
      btnQuanLiDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
      btnQuanLiDocGia.setText("QUAN LI DOC GIA");
      btnQuanLiDocGia.setFocusable(false);
      btnQuanLiDocGia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      btnQuanLiDocGia.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
      btnQuanLiDocGia.setIconTextGap(20);
      btnQuanLiDocGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnQuanLiDocGiaActionPerformed(evt);
         }
      });

      btnQuanLiMuonTra.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
      btnQuanLiMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
      btnQuanLiMuonTra.setText("QUAN LI MUON TRA");
      btnQuanLiMuonTra.setFocusable(false);
      btnQuanLiMuonTra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      btnQuanLiMuonTra.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
      btnQuanLiMuonTra.setIconTextGap(20);
      btnQuanLiMuonTra.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnQuanLiMuonTraActionPerformed(evt);
         }
      });

      btnTraCuu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
      btnTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/block-user.png"))); // NOI18N
      btnTraCuu.setText("TRA CUU");
      btnTraCuu.setFocusable(false);
      btnTraCuu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      btnTraCuu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
      btnTraCuu.setIconTextGap(20);
      btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTraCuuActionPerformed(evt);
         }
      });

      btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
      btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
      btnThongKe.setText("THONG KE");
      btnThongKe.setFocusable(false);
      btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
      btnThongKe.setIconTextGap(20);
      btnThongKe.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThongKeActionPerformed(evt);
         }
      });

      btnTraCuu1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
      btnTraCuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searching.png"))); // NOI18N
      btnTraCuu1.setText("TRA CUU");
      btnTraCuu1.setFocusable(false);
      btnTraCuu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      btnTraCuu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
      btnTraCuu1.setIconTextGap(20);
      btnTraCuu1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTraCuu1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnTraCuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(btnQuanLiMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                           .addComponent(btnQuanLiDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(btnQuanLiSach, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                     .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnTraCuu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addComponent(jSeparator1)
               .addComponent(jSeparator5))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(btnQuanLiSach)
            .addGap(41, 41, 41)
            .addComponent(btnQuanLiDocGia)
            .addGap(27, 27, 27)
            .addComponent(btnQuanLiMuonTra)
            .addGap(54, 54, 54)
            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(49, 49, 49)
            .addComponent(btnThongKe)
            .addGap(29, 29, 29)
            .addComponent(btnTraCuu1)
            .addGap(42, 42, 42)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(39, 39, 39)
            .addComponent(btnTraCuu)
            .addContainerGap(171, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("QUAN LY THU VIEN");
      jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange.png"))); // NOI18N

      lbMaThuThu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      lbMaThuThu.setText("TT001");

      lbHoTen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      lbHoTen.setText("NOUVEN");

      jButton1.setBackground(new java.awt.Color(51, 153, 255));
      jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lbMaThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(46, 46, 46)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(46, 46, 46))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(lbMaThuThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(21, 21, 21))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
         .addComponent(jSeparator4)
      );

      jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(301, 301, 301)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                  .addGap(22, 22, 22))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jSeparator2))
                  .addContainerGap())))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tpnMain))
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGap(11, 11, 11))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(tpnMain)
                  .addContainerGap())
               .addComponent(jSeparator3)))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnQuanLiDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiDocGiaActionPerformed
		tpnMain.removeAll();
		QuanLiDocGiaPn view = new QuanLiDocGiaPn();
		tpnMain.addTab("QUAN LI DOC GIA", view);
		tpnMain.setSelectedComponent(view);
   }//GEN-LAST:event_btnQuanLiDocGiaActionPerformed

   private void btnQuanLiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiSachActionPerformed
		tpnMain.removeAll();
		QuanLiSachPn quanLiSachPn = new QuanLiSachPn();
		tpnMain.addTab("QUAN LI SACH", quanLiSachPn);
		tpnMain.setSelectedComponent(quanLiSachPn);
		QuanLiDanhMucPn quanLiDanhMucPn = new QuanLiDanhMucPn();
		tpnMain.addTab("QUAN LI DANH MUC", quanLiDanhMucPn);
//		LoginFrm loginFrm = new LoginFrm();
//		loginFrm.setVisible(true);
      // TODO add your handling code here:
   }//GEN-LAST:event_btnQuanLiSachActionPerformed

   private void btnQuanLiMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiMuonTraActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnQuanLiMuonTraActionPerformed

   private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnTraCuuActionPerformed

   private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnThongKeActionPerformed

   private void btnTraCuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuu1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnTraCuu1ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(mainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new mainFrm().setVisible(true);
			}
		});
		long miliS = System.currentTimeMillis();
		Date date = new Date(miliS);
		Date dateNd = Date.valueOf("2021-11-25");
		System.out.println(date);
		System.out.println(dateNd);
		int hash = dateNd.hashCode() - date.hashCode();
		System.out.println(hash / (24 * 60 * 60 * 1000));
		System.out.println(date.compareTo(dateNd));
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnQuanLiDocGia;
   private javax.swing.JButton btnQuanLiMuonTra;
   private javax.swing.JButton btnQuanLiSach;
   private javax.swing.JButton btnThongKe;
   private javax.swing.JButton btnTraCuu;
   private javax.swing.JButton btnTraCuu1;
   private javax.swing.JButton jButton1;
   private javax.swing.JFrame jFrame1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSeparator jSeparator4;
   private javax.swing.JSeparator jSeparator5;
   private javax.swing.JLabel lbHoTen;
   private javax.swing.JLabel lbMaThuThu;
   private javax.swing.JTabbedPane tpnMain;
   // End of variables declaration//GEN-END:variables
}
