/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ThuThuDao;
import foo.MessDialog;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.DocGia;
import models.ThuThu;

/**
 *
 * @author doquy
 */
public class MainAdFrm extends javax.swing.JFrame {

	/**
	 * Creates new form MainAdFrm
	 */
	private ArrayList<ThuThu> list;
	private String[] headerTbl = {
		"MÃ THỦ ",
		"HỌ TÊN",
		"EMAIL",
		"SDT",
		"USERNAME",
		"PASSWORD",
	};
	private DefaultTableModel model = new DefaultTableModel();
	private ThuThuDao dao = new ThuThuDao();
	public MainAdFrm() {
		initComponents();
		this.setLocationRelativeTo(null);
		list = dao.selectAll();
		initTbl(model, tblThuThu, headerTbl, list);
	}

	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<ThuThu> list){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		list.forEach((elmt) -> {
			model.addRow(new Object[]{
				elmt.getMaThuThu(),
				elmt.getHoTen(),
				elmt.getEmail(),
				elmt.getSdt(),
				elmt.getUsername(),
				"*********",
			});
		});
		tbl.setModel(model);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblThuThu = new javax.swing.JTable();
      btnThem1 = new javax.swing.JButton();
      jSeparator2 = new javax.swing.JSeparator();
      btnSua = new javax.swing.JButton();
      btnLuu = new javax.swing.JButton();
      btnXoa = new javax.swing.JButton();
      btnTimKiem = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JSeparator();
      btnShow = new javax.swing.JButton();
      txtPassword = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      txtUsername = new javax.swing.JTextField();
      txtSdt = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtMaThuThu = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtEmail = new javax.swing.JTextField();
      txtHoten = new javax.swing.JTextField();
      btnLogout = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 204));

      jPanel1.setBackground(new java.awt.Color(255, 255, 204));

      tblThuThu.setAutoCreateRowSorter(true);
      tblThuThu.setBackground(new java.awt.Color(255, 255, 204));
      tblThuThu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblThuThu.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblThuThu.setAlignmentX(1.0F);
      tblThuThu.setAlignmentY(1.0F);
      tblThuThu.setRowHeight(30);
      tblThuThu.setRowMargin(3);
      tblThuThu.setShowGrid(true);
      tblThuThu.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblThuThuMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblThuThu);

      btnThem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
      btnThem1.setText("THEM");
      btnThem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnThem1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnThem1.setIconTextGap(20);
      btnThem1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThem1ActionPerformed(evt);
         }
      });

      btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
      btnSua.setText("SUA");
      btnSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnSua.setIconTextGap(20);
      btnSua.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSuaActionPerformed(evt);
         }
      });

      btnLuu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
      btnLuu.setText("LUU");
      btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnLuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnLuu.setIconTextGap(20);
      btnLuu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLuuActionPerformed(evt);
         }
      });

      btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove (1).png"))); // NOI18N
      btnXoa.setText("XOA");
      btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnXoa.setIconTextGap(20);
      btnXoa.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaActionPerformed(evt);
         }
      });

      btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searching.png"))); // NOI18N
      btnTimKiem.setText("TIM KIEM");
      btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnTimKiem.setIconTextGap(20);
      btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTimKiemActionPerformed(evt);
         }
      });

      btnShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password.png"))); // NOI18N
      btnShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnShow.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnShow.setIconTextGap(20);
      btnShow.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnShowActionPerformed(evt);
         }
      });

      txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      txtPassword.setText("**************");

      jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel3.setText("Password:");

      jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel6.setText("Username:");

      txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtUsername.setText("username");

      txtSdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtSdt.setText("0794035848");

      jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel2.setText("SDT:");

      txtMaThuThu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaThuThu.setText("TT001");
      txtMaThuThu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaThuThuActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel1.setText("Mã Thủ Thư:");

      jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel5.setText("Họ Tên:");

      jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel4.setText("Email:");

      txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtEmail.setText("vuthinhnguyen@ecu.com");

      txtHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtHoten.setText("ooouvnouven");

      btnLogout.setBackground(new java.awt.Color(51, 153, 255));
      btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
      btnLogout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLogoutActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(69, 69, 69)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(44, 44, 44)
                  .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(45, 45, 45)
                  .addComponent(btnXoa)
                  .addGap(27, 27, 27)
                  .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(36, 36, 36)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtMaThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(114, 114, 114)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(318, 318, 318))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                           .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGap(49, 49, 49)
                           .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                           .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                 .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addComponent(btnShow)))))))
               .addComponent(jSeparator2)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(125, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(7, 7, 7)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtMaThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(19, 19, 19)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(24, 24, 24)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(35, 35, 35)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(32, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void txtMaThuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaThuThuActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaThuThuActionPerformed

   private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
		String maThuThu = txtMaThuThu.getText();
		if(maThuThu.equals("")){
			return;
		}
		String str = MessDialog.showEnterText(this, "Nhập mật khẩu?", ":))");
		if(str.equals(dao.showPass("TT003"))){
			txtPassword.setText(dao.showPass(maThuThu));
		}
   }//GEN-LAST:event_btnShowActionPerformed

   private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
		String maThuThu = txtMaThuThu.getText();
		String hoTen = txtHoten.getText();
		String email = txtEmail.getText();
		String sdt = txtSdt.getText();
		String username = txtUsername.getText();
		String password = txtPassword.getText();
		ThuThu thuThu = new ThuThu(maThuThu, hoTen, email, sdt, username, password, email);
		int choose = MessDialog.showComfirmDialog(this, "Sửa??", "comfirm!!");
		if(choose == 0){
			if(dao.update(thuThu) == true){
				MessDialog.showMessDialog(this, "Sửa thành công!!!", "info!!");
				list = dao.selectAll();
				initTbl(model, tblThuThu, headerTbl, list);
			}else{
				MessDialog.showErrorDialog(this, "Sửa thất baij!!!", "ERRor!!");
			}
		}
   }//GEN-LAST:event_btnSuaActionPerformed

   private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
   }//GEN-LAST:event_btnLuuActionPerformed

   private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
      String maThuThu = txtMaThuThu.getText();
      if(maThuThu.equals("")){
         MessDialog.showErrorDialog(this, "CAN CHON MA BAN DOC DE XOA", "INFO");
         return;
      }
      int choose = MessDialog.showComfirmDialog(this, "XOA ?", "COMFIRM");
      if(choose == 0){
         boolean isDelete = dao.delete(maThuThu);
         if(isDelete == true){
            list = dao.selectAll();
            initTbl(model, tblThuThu, headerTbl, list);
            MessDialog.showMessDialog(this, "XOA THANH CONG!!!", "INFO");
         }else{
            MessDialog.showErrorDialog(this, "THAT BAI!!!", "ERROR");
         }
      }
   }//GEN-LAST:event_btnXoaActionPerformed

   private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
		String maThuThu = txtMaThuThu.getText();
      if(maThuThu.equals("")){
         MessDialog.showErrorDialog(this, "Cần nhập mã thủ thu!!", "ERROR");
         return;
      }
		ThuThu thuThu = dao.findById(maThuThu);
      if(thuThu == null){
         MessDialog.showMessDialog(this, "không tìm thấy !!", "ERROR");
			return;
      }else{
            txtMaThuThu.setText(thuThu.getMaThuThu());
            txtEmail.setText(thuThu.getEmail());
            txtHoten.setText(thuThu.getHoTen());
            txtPassword.setText("********");
            txtUsername.setText(thuThu.getUsername());
            txtSdt.setText(thuThu.getSdt());
      }
   }//GEN-LAST:event_btnTimKiemActionPerformed

   private void tblThuThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuThuMouseClicked
      int row = tblThuThu.getSelectedRow();
      if(row >= 0){
         ThuThu thuThu = dao.findById(tblThuThu.getValueAt(row, 0).toString());
         if(thuThu != null){
            txtMaThuThu.setText(thuThu.getMaThuThu());
            txtEmail.setText(thuThu.getEmail());
            txtHoten.setText(thuThu.getHoTen());
            txtPassword.setText("********");
            txtUsername.setText(thuThu.getUsername());
            txtSdt.setText(thuThu.getSdt());
         }
      }
   }//GEN-LAST:event_tblThuThuMouseClicked

   private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
		String maThuThu = txtMaThuThu.getText();
		String hoTen = txtHoten.getText();
		String email = txtEmail.getText();
		String sdt = txtSdt.getText();
		String username = txtUsername.getText();
		String password = txtPassword.getText();
		if(maThuThu.equals("") || username.equals("") || password.equals("")){
			MessDialog.showErrorDialog(this, "Cần nhập đầy đủ các trường!!", "Error!");
			return;
		}
		int choose = MessDialog.showComfirmDialog(this, "Thêm mới thủ thư?", "comfirm!");
		if(choose == 0){
			ThuThu thuThu = new ThuThu(maThuThu, hoTen, email, sdt, username, password, email);
			if(dao.insert(thuThu) == true){
				MessDialog.showErrorDialog(this, "Thêm thất bại!!!", "ERROR!");
			}else{
				MessDialog.showComfirmDialog(this, "Thêm thành !!!", "SUCCS!");
				list.add(thuThu);
				initTbl(model, tblThuThu, headerTbl, list);
			}
			return;
		}
		return;
   }//GEN-LAST:event_btnThem1ActionPerformed

   private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      this.dispose();
      new LoginFrm().setVisible(true);
   }//GEN-LAST:event_btnLogoutActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainAdFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainAdFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainAdFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainAdFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainAdFrm().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnLogout;
   private javax.swing.JButton btnLuu;
   private javax.swing.JButton btnShow;
   private javax.swing.JButton btnSua;
   private javax.swing.JButton btnThem1;
   private javax.swing.JButton btnTimKiem;
   private javax.swing.JButton btnXoa;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JTable tblThuThu;
   private javax.swing.JTextField txtEmail;
   private javax.swing.JTextField txtHoten;
   private javax.swing.JTextField txtMaThuThu;
   private javax.swing.JTextField txtPassword;
   private javax.swing.JTextField txtSdt;
   private javax.swing.JTextField txtUsername;
   // End of variables declaration//GEN-END:variables
}
