/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.DanhMucDao;
import controllers.DocGiaDao;
import controllers.MuonTraDao;
import controllers.SachDao;
import foo.Bar;
import foo.MessDialog;
import foo.Validator;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.DanhMuc;
import models.DocGia;
import models.MuonTra;
import models.Sach;

/**
 *
 * @author doquy
 */
public class QuanLiMuonTraPn extends javax.swing.JPanel {

	/**
	 * Creates new form FisrtPn
	 */
	private ArrayList<MuonTra> list;
	private String[] headerTbl = {
		"MA SACH",
		"MA DOC GIA",
		"MA THU THU",
		"NGAY MUON",
		"SO NGAY MUON",
		"NGAY THUC TRA",
	};
	private boolean btnThemSua = false;
	private String maThuThu;
	private DefaultTableModel model = new DefaultTableModel();
	private MuonTraDao dao = new MuonTraDao();
	private SachDao sachDao = new SachDao();
	private DocGiaDao docGiaDao = new DocGiaDao();
	public QuanLiMuonTraPn(String maThuThu) {
		list = new ArrayList<>();
		list = dao.selectAll();
		initComponents();
		initTbl(model, tblMuonTra, headerTbl, list);
		this.maThuThu = maThuThu;
	}
	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<MuonTra> list){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		list.forEach((elmt) -> {
			String ngayThucTra = elmt.getNgayThucTra().toString();
			if(ngayThucTra.equals("2000-02-02")){
				ngayThucTra = "null";
			}
			model.addRow(new Object[]{
				elmt.getMaSach(),
				elmt.getMaDocGia(),
				elmt.getMaThuThu(),
				elmt.getNgayMuon(),
				elmt.getSoNgayMuon(),
				ngayThucTra
			});
		});
		tbl.setModel(model);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator2 = new javax.swing.JSeparator();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblMuonTra = new javax.swing.JTable();
      jLabel12 = new javax.swing.JLabel();
      spnSoNgayMuon = new javax.swing.JSpinner();
      txtMaSach = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtMaDocGia = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      btnThem = new javax.swing.JButton();
      btnMuonSach = new javax.swing.JButton();
      btnTraSach = new javax.swing.JButton();
      btnXoa = new javax.swing.JButton();
      btnTimKiem = new javax.swing.JButton();
      jSeparator4 = new javax.swing.JSeparator();
      lbHoTen = new javax.swing.JLabel();
      lbNgaySinh = new javax.swing.JLabel();
      lbDiaChi = new javax.swing.JLabel();
      lbGioiTinh = new javax.swing.JLabel();
      lbEmail = new javax.swing.JLabel();
      lbTenSach = new javax.swing.JLabel();
      lbTacGia = new javax.swing.JLabel();
      lbNXB = new javax.swing.JLabel();
      jSeparator3 = new javax.swing.JSeparator();
      jSeparator5 = new javax.swing.JSeparator();
      txtNgayThucTra = new javax.swing.JLabel();
      txtTenDocGia = new javax.swing.JLabel();
      txtTenSach = new javax.swing.JLabel();
      txtNgayMuon = new javax.swing.JLabel();
      txtTinhTrang = new javax.swing.JLabel();
      lbNXB1 = new javax.swing.JLabel();

      setBackground(new java.awt.Color(255, 255, 204));

      tblMuonTra.setAutoCreateRowSorter(true);
      tblMuonTra.setBackground(new java.awt.Color(255, 255, 204));
      tblMuonTra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblMuonTra.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblMuonTra.setAlignmentX(1.0F);
      tblMuonTra.setAlignmentY(1.0F);
      tblMuonTra.setRowHeight(30);
      tblMuonTra.setRowMargin(3);
      tblMuonTra.setShowGrid(true);
      tblMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblMuonTraMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblMuonTra);

      jLabel12.setBackground(new java.awt.Color(184, 152, 96));
      jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel12.setText("SO NGAY MUON");

      spnSoNgayMuon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

      txtMaSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaSach.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaSachActionPerformed(evt);
         }
      });
      txtMaSach.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtMaSachKeyPressed(evt);
         }
      });

      jLabel6.setBackground(new java.awt.Color(184, 152, 96));
      jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel6.setText("MA SACH");

      txtMaDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaDocGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaDocGiaActionPerformed(evt);
         }
      });
      txtMaDocGia.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtMaDocGiaKeyPressed(evt);
         }
      });

      jLabel8.setBackground(new java.awt.Color(184, 152, 96));
      jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel8.setText("MA DOC GIA");

      btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
      btnThem.setText("THEM");
      btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnThem.setIconTextGap(20);
      btnThem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThemActionPerformed(evt);
         }
      });

      btnMuonSach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
      btnMuonSach.setText("MUON SACH");
      btnMuonSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnMuonSach.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnMuonSach.setIconTextGap(20);
      btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnMuonSachActionPerformed(evt);
         }
      });

      btnTraSach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnTraSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
      btnTraSach.setText("TRA SACH");
      btnTraSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnTraSach.setIconTextGap(20);
      btnTraSach.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTraSachActionPerformed(evt);
         }
      });

      btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove (1).png"))); // NOI18N
      btnXoa.setText("XOA");
      btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnXoa.setIconTextGap(20);
      btnXoa.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaActionPerformed(evt);
         }
      });

      btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searching.png"))); // NOI18N
      btnTimKiem.setText("TIM KIEM");
      btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnTimKiem.setIconTextGap(20);
      btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTimKiemActionPerformed(evt);
         }
      });

      jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

      lbHoTen.setBackground(new java.awt.Color(255, 255, 255));
      lbHoTen.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbHoTen.setText("jLabel1");

      lbNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
      lbNgaySinh.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbNgaySinh.setText("jLabel1");

      lbDiaChi.setBackground(new java.awt.Color(255, 255, 255));
      lbDiaChi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbDiaChi.setText("jLabel1");

      lbGioiTinh.setBackground(new java.awt.Color(255, 255, 255));
      lbGioiTinh.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbGioiTinh.setText("jLabel1");

      lbEmail.setBackground(new java.awt.Color(255, 255, 255));
      lbEmail.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbEmail.setText("jLabel1");

      lbTenSach.setBackground(new java.awt.Color(255, 255, 255));
      lbTenSach.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbTenSach.setText("jLabel1");

      lbTacGia.setBackground(new java.awt.Color(255, 255, 255));
      lbTacGia.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbTacGia.setText("jLabel1");

      lbNXB.setBackground(new java.awt.Color(255, 255, 255));
      lbNXB.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbNXB.setText("jLabel1");

      jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

      txtNgayThucTra.setBackground(new java.awt.Color(255, 255, 255));
      txtNgayThucTra.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      txtNgayThucTra.setText("jLabel1");

      txtTenDocGia.setBackground(new java.awt.Color(255, 255, 255));
      txtTenDocGia.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      txtTenDocGia.setText("jLabel1");

      txtTenSach.setBackground(new java.awt.Color(255, 255, 255));
      txtTenSach.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      txtTenSach.setText("jLabel1");

      txtNgayMuon.setBackground(new java.awt.Color(255, 255, 255));
      txtNgayMuon.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      txtNgayMuon.setText("jLabel1");

      txtTinhTrang.setBackground(new java.awt.Color(255, 255, 255));
      txtTinhTrang.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      txtTinhTrang.setText("jLabel1");

      lbNXB1.setBackground(new java.awt.Color(255, 255, 255));
      lbNXB1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      lbNXB1.setForeground(new java.awt.Color(255, 0, 0));
      lbNXB1.setText("* Chỉ được mượn tối đa 3 cuốn sách!!");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jSeparator3)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jSeparator2)
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(70, 70, 70)
                  .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(54, 54, 54)
                  .addComponent(btnTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(58, 58, 58)
                  .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(60, 60, 60)
                  .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(lbDiaChi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(lbGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(lbNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(lbHoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(55, 55, 55)
                  .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(spnSoNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                           .addComponent(lbTacGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(lbNXB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addComponent(lbNXB1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(46, 46, 46)
                  .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(36, 36, 36)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtNgayThucTra, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(48, 48, 48))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(txtNgayThucTra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(28, 28, 28)
                  .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(74, 74, 74))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(spnSoNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(lbNXB1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(68, 68, 68)))
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnThem)
               .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(107, 107, 107))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaSachActionPerformed

   private void txtMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDocGiaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaActionPerformed

   private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
		btnMuonSach.setEnabled(true);
		JTextField[] listTxt = {
   		txtMaSach,
		};
		Bar.resetTxt(listTxt);
   }//GEN-LAST:event_btnThemActionPerformed

   private void tblMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMuonTraMouseClicked
		int row = tblMuonTra.getSelectedRow();
		if(row >= 0){
			String maSach = tblMuonTra.getValueAt(row, 0).toString();
			String maDocGia = tblMuonTra.getValueAt(row, 1).toString();
			MuonTra muonTra = dao.findById(maSach, maDocGia);
			if(muonTra == null){
				System.out.println("hshahah");
				return;
			}
			/*ma sach, madocgia, songaymuon, ngaymuon, tinhtrang, ngaythuctra, tensach, tenbandoc*/
			txtMaDocGia.setText(maDocGia);
			txtMaSach.setText(maSach);
			spnSoNgayMuon.setValue(muonTra.getSoNgayMuon());
			txtNgayMuon.setText("NGAY MUON: "+muonTra.getNgayMuon().toString());
			if(muonTra.getNgayThucTra().toString().equals("2000-02-02")){
				txtNgayThucTra.setText("NGAY THUC TRA: null");
				Date curDate = new Date(System.currentTimeMillis());
				Date ngayMuon = muonTra.getNgayMuon();
				int hash = (-1) * (ngayMuon.hashCode() - curDate.hashCode()) / (24 * 60 * 60 * 1000);
				if((hash - muonTra.getSoNgayMuon()) <= 0){
					txtTinhTrang.setText("TINH TRANG: chua tra");
				}else{
					txtTinhTrang.setText("TINH TRANG: QUA HAN");
				}
			}else{
				txtNgayThucTra.setText("NGAY THUC TRA: "+ muonTra.getNgayThucTra().toString());
				txtTinhTrang.setText("TINH TRANG: da tra");
			}
			Sach sach = sachDao.findById(maSach);
			if(sach != null){
				txtTenSach.setText("TEN SACH: "+sach.getTenSach());
				lbTacGia.setText("Tac Gia: " + sach.getTacGia());
				lbTenSach.setText("Ten Sach : " + sach.getTenSach());
				lbNXB.setText("NXB : " + sach.getNxb());
			}else{
				txtTenSach.setText("hahahah");
				lbTacGia.setText("");
				lbTenSach.setText("");
				lbNXB.setText("");
			}
			DocGia docGia = docGiaDao.findById(maDocGia);
			if(docGia!= null){
				txtTenDocGia.setText("TEN DOC GIA: "+docGia.getHoTen());
				lbHoTen.setText("HO TEN: "+docGia.getHoTen());
				lbDiaChi.setText("DIA CHI : "+docGia.getDiaChi());
				lbEmail.setText("EMAIL : "+docGia.getEmail());
				lbNgaySinh.setText("NGAY SINH: " + docGia.getNgaySinh());
				if(docGia.getGoiTinh() == 1){
					lbGioiTinh.setText("GIOI TINH: nam");
				}else{
					lbGioiTinh.setText("GIOI TINH: nu");
				}
				}else{
					txtTenDocGia.setText("hahaha");
					lbHoTen.setText("");
					lbDiaChi.setText("");
					lbEmail.setText("");
					lbGioiTinh.setText("");
					lbNgaySinh.setText("");
				}
		}
   }//GEN-LAST:event_tblMuonTraMouseClicked

   private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed
		JTextField[] listTxt = {
   		txtMaDocGia,
   		txtMaSach,
		};
		if((int)spnSoNgayMuon.getValue() <= 0){
				MessDialog.showErrorDialog(this, "SO NGAY MUON PHAI LON HON 0!!", "ERROR");
				return;
		}
		for(JTextField i: listTxt){
			if(i.getText().equals("")){
				MessDialog.showErrorDialog(this, "CAN NHAP DAY DU CAC TRUONG!!", "ERROR");
				return;
			}
		}
			String maSach = txtMaSach.getText();
			String maDocGia = txtMaDocGia.getText();
			int soSachChuTra = dao.countDaMuon(maDocGia) - dao.countDaTra(maDocGia);
			if(soSachChuTra >= 3){
				MessDialog.showErrorDialog(this, "CHỈ ĐƯỢC MƯƠN TỐi ĐA 3 CUỐN!!", "ERROR");
				return;
			}
			String maThuThu = this.maThuThu;
			Date ngayMuon = new Date(System.currentTimeMillis());
			int soNgayMuon = (int)spnSoNgayMuon.getValue();
			MuonTra muonTra = new MuonTra(maSach, maDocGia, maThuThu, ngayMuon, soNgayMuon);
			boolean isInsert = dao.insert(muonTra);
			if(isInsert == true){
				MessDialog.showMessDialog(this , "THEM THANH CONG!!", "INFO");
				list = dao.selectAll();
				initTbl(model, tblMuonTra, headerTbl, list);
			}else{
				MessDialog.showErrorDialog(this, "THEM THAT BAI!!", "ERROR");
			}
			
   }//GEN-LAST:event_btnMuonSachActionPerformed

   private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
		if(txtNgayThucTra.getText().equals("NGAY THUC TRA: null")){
			String maSach = txtMaSach.getText();
			String maDocGia = txtMaDocGia.getText();
			String maThuThu = this.maThuThu;
			Date ngayThucTra = new Date(System.currentTimeMillis());
			int choose = MessDialog.showComfirmDialog(this, "TRA SACH?", "COMFIRM");
			if(choose == 0){
				boolean isUpdate= dao.update(maSach, maDocGia, ngayThucTra);
				if(isUpdate == true){
					MessDialog.showMessDialog(this , "TRA THANH CONG!!", "INFO");
					list = dao.selectAll();
					initTbl(model, tblMuonTra, headerTbl, list);
				}else{
					MessDialog.showErrorDialog(this, "TRA THAT BAI!!", "ERROR");
				}
			}
		}else{
			MessDialog.showMessDialog(this, "SACH DA DUOC TRA!!!", "INFO");
		}
   }//GEN-LAST:event_btnTraSachActionPerformed

   private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
		String maDocGia = txtMaDocGia.getText();
		String maSach = txtMaSach.getText();
		if(maDocGia.equals("")){
			MessDialog.showErrorDialog(this, "CAN NHAP MA DOC GIA VA MA SACH DE XOA!!", "INFO");
			return;
		}
		int choose = MessDialog.showComfirmDialog(this, "XOA ?", "COMFIRM");
		if(choose == 0){
			boolean isDelete = dao.delete(maSach, maDocGia);
			if(isDelete == true){
				list = dao.selectAll();
				initTbl(model, tblMuonTra, headerTbl, list);
				MessDialog.showMessDialog(this, "XOA THANH CONG!!!", "INFO");
			}else{
				MessDialog.showErrorDialog(this, "THAT BAI!!!", "ERROR");
			}
		}
   }//GEN-LAST:event_btnXoaActionPerformed

   private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
		String maDocGia = txtMaDocGia.getText();
		String maSach = txtMaSach.getText();
		if(maDocGia.equals("") || maSach.equals("")){
			MessDialog.showErrorDialog(this, "CAN NHAP MA DOC GIA & MA SACH!!", "ERROR");
			return;
		}
		MuonTra muonTra = dao.findById(maSach, maDocGia);
		if(muonTra == null){
			MessDialog.showMessDialog(this, "KHONG TIM THAY!!", "ERROR");
		}else{
			txtMaDocGia.setText(maDocGia);
			txtMaSach.setText(maSach);
			spnSoNgayMuon.setValue(muonTra.getSoNgayMuon());
			txtNgayMuon.setText("NGAY MUON: "+muonTra.getNgayMuon().toString());
			if(muonTra.getNgayThucTra().toString().equals("2000-02-02")){
				txtNgayThucTra.setText("NGAY THUC TRA: null");
				Date curDate = new Date(System.currentTimeMillis());
				Date ngayMuon = muonTra.getNgayMuon();
				int hash = (-1) * (ngayMuon.hashCode() - curDate.hashCode()) / (24 * 60 * 60 * 1000);
				if((hash - muonTra.getSoNgayMuon()) <= 0){
					txtTinhTrang.setText("TINH TRANG: chua tra");
				}else{
					txtTinhTrang.setText("TINH TRANG: qua han");
				}
			}else{
				txtNgayThucTra.setText("NGAY THUC TRA: "+muonTra.getNgayThucTra().toString());
				txtTinhTrang.setText("TINH TRANG: da tra");
			}
			Sach sach = sachDao.findById(maSach);
			if(sach != null){
				txtTenSach.setText("TEN SACH: "+sach.getTenSach());
				lbTacGia.setText("Tac Gia: " + sach.getTacGia());
				lbTenSach.setText("Ten Sach : " + sach.getTenSach());
				lbNXB.setText("NXB : " + sach.getNxb());
			}else{
				txtTenSach.setText("hahahah");
				lbTacGia.setText("");
				lbTenSach.setText("");
				lbNXB.setText("");
			}
			DocGia docGia = docGiaDao.findById(maDocGia);
			if(docGia!= null){
				txtTenDocGia.setText("TEN DOC GIA: "+docGia.getHoTen());
				lbHoTen.setText("HO TEN: "+docGia.getHoTen());
				lbDiaChi.setText("DIA CHI : "+docGia.getDiaChi());
				lbEmail.setText("EMAIL : "+docGia.getEmail());
				lbNgaySinh.setText("NGAY SINH: " + docGia.getNgaySinh());
				if(docGia.getGoiTinh() == 1){
					lbGioiTinh.setText("GIOI TINH: nam");
				}else{
					lbGioiTinh.setText("GIOI TINH: nu");
				}
				}else{
					txtTenDocGia.setText("hahaha");
					lbHoTen.setText("");
					lbDiaChi.setText("");
					lbEmail.setText("");
					lbGioiTinh.setText("");
					lbNgaySinh.setText("");
				}
		}
   }//GEN-LAST:event_btnTimKiemActionPerformed

   private void txtMaDocGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDocGiaKeyPressed
		String maDocGia = txtMaDocGia.getText();
		DocGia docGia = docGiaDao.findById(maDocGia);
		if(docGia != null){
			lbHoTen.setText("HO TEN: "+docGia.getHoTen());
			lbDiaChi.setText("DIA CHI : "+docGia.getDiaChi());
			lbEmail.setText("EMAIL : "+docGia.getEmail());
			lbNgaySinh.setText("NGAY SINH: " + docGia.getNgaySinh());
			if(docGia.getGoiTinh() == 1){
				lbGioiTinh.setText("GIOI TINH: nam");
			}else{
				lbGioiTinh.setText("GIOI TINH: nu");
			}
			ArrayList<MuonTra> muonTraList = dao.findByIdDocGia(docGia.getMaDocGia());
			initTbl(model, tblMuonTra, headerTbl, muonTraList);
		}else{
			initTbl(model, tblMuonTra, headerTbl, list);
			lbHoTen.setText("");
			lbDiaChi.setText("");
			lbEmail.setText("");
			lbGioiTinh.setText("");
			lbNgaySinh.setText("");
		}
   }//GEN-LAST:event_txtMaDocGiaKeyPressed

   private void txtMaSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSachKeyPressed
		String maSach = txtMaSach.getText();
		Sach sach = sachDao.findById(maSach);
		if(sach != null){
			lbTacGia.setText("Tac Gia: " + sach.getTacGia());
			lbTenSach.setText("Ten Sach : " + sach.getTenSach());
			lbNXB.setText("NXB : " + sach.getNxb());
		}else{
			lbTacGia.setText("");
			lbTenSach.setText("");
			lbNXB.setText("");
		}
   }//GEN-LAST:event_txtMaSachKeyPressed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnMuonSach;
   private javax.swing.JButton btnThem;
   private javax.swing.JButton btnTimKiem;
   private javax.swing.JButton btnTraSach;
   private javax.swing.JButton btnXoa;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSeparator jSeparator4;
   private javax.swing.JSeparator jSeparator5;
   private javax.swing.JLabel lbDiaChi;
   private javax.swing.JLabel lbEmail;
   private javax.swing.JLabel lbGioiTinh;
   private javax.swing.JLabel lbHoTen;
   private javax.swing.JLabel lbNXB;
   private javax.swing.JLabel lbNXB1;
   private javax.swing.JLabel lbNgaySinh;
   private javax.swing.JLabel lbTacGia;
   private javax.swing.JLabel lbTenSach;
   private javax.swing.JSpinner spnSoNgayMuon;
   private javax.swing.JTable tblMuonTra;
   private javax.swing.JTextField txtMaDocGia;
   private javax.swing.JTextField txtMaSach;
   private javax.swing.JLabel txtNgayMuon;
   private javax.swing.JLabel txtNgayThucTra;
   private javax.swing.JLabel txtTenDocGia;
   private javax.swing.JLabel txtTenSach;
   private javax.swing.JLabel txtTinhTrang;
   // End of variables declaration//GEN-END:variables
}
