/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.DocGiaDao;
import foo.Bar;
import foo.MessDialog;
import foo.Validator;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.DocGia;

/**
 *
 * @author doquy
 */
public class QuanLiDocGiaPn extends javax.swing.JPanel {

	/**
	 * Creates new form FisrtPn
	 */
	private ArrayList<DocGia> list;
	private String[] headerTbl = {
		"MA DOC GIA",
		"HO TEN",
		"NGAY SINH",
		"GIOI TINH",
		"EMAIL",
	};
	private DefaultTableModel model = new DefaultTableModel();
	private DocGiaDao dao = new DocGiaDao();
	private boolean  toggleLuu = false;
	public QuanLiDocGiaPn() {
		list = new ArrayList<>();
		list = dao.selectAll();
		initComponents();
		initTbl(model, tblDocGia, headerTbl, list);
		this.setDisable();
	}
	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<DocGia> list){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		list.forEach((elmt) -> {
			String gioiTinh = "Nam";
			if(elmt.getGoiTinh() == 0){
				gioiTinh = "nu";
			}
			model.addRow(new Object[]{
				elmt.getMaDocGia(),
				elmt.getHoTen(),
				elmt.getNgaySinh(),
				gioiTinh,
				elmt.getEmail(),
			});
		});
		tbl.setModel(model);
	}
	public void setEnable(){
   		txtDiaChi.setEnabled(true);
   		txtEmail.setEnabled(true);
   		txtHoTen.setEnabled(true);
   		txtMaDocGia.setEnabled(true);
   		txtNgaySinh.setEnabled(true);
   		txtSdt.setEnabled(true);
			rdbNam.setEnabled(true);
			rdbNu.setEnabled(true);
	}
	public void setDisable(){
   		txtDiaChi.setEnabled(false);
   		txtEmail.setEnabled(false);
   		txtHoTen.setEnabled(false);
   		txtMaDocGia.setEnabled(true);
   		txtNgaySinh.setEnabled(false);
   		txtSdt.setEnabled(false);
			rdbNam.setEnabled(false);
			rdbNu.setEnabled(false);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator2 = new javax.swing.JSeparator();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblDocGia = new javax.swing.JTable();
      jLabel9 = new javax.swing.JLabel();
      rdbNam = new javax.swing.JRadioButton();
      rdbNu = new javax.swing.JRadioButton();
      txtNgaySinh = new javax.swing.JTextField();
      jLabel10 = new javax.swing.JLabel();
      txtHoTen = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      txtMaDocGia = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      jLabel16 = new javax.swing.JLabel();
      txtDiaChi = new javax.swing.JTextField();
      txtEmail = new javax.swing.JTextField();
      jLabel14 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      txtSdt = new javax.swing.JTextField();
      btnThem = new javax.swing.JButton();
      btnSua = new javax.swing.JButton();
      btnLuu = new javax.swing.JButton();
      btnXoa = new javax.swing.JButton();
      btnTimKiem = new javax.swing.JButton();
      jSeparator5 = new javax.swing.JSeparator();

      setBackground(new java.awt.Color(255, 255, 204));

      tblDocGia.setAutoCreateRowSorter(true);
      tblDocGia.setBackground(new java.awt.Color(255, 255, 204));
      tblDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblDocGia.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblDocGia.setAlignmentX(1.0F);
      tblDocGia.setAlignmentY(1.0F);
      tblDocGia.setRowHeight(30);
      tblDocGia.setRowMargin(3);
      tblDocGia.setShowGrid(true);
      tblDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblDocGiaMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblDocGia);

      jLabel9.setBackground(new java.awt.Color(184, 152, 96));
      jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel9.setText("GIOI TINH");

      rdbNam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      rdbNam.setText("NAM");
      rdbNam.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rdbNamActionPerformed(evt);
         }
      });

      rdbNu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      rdbNu.setSelected(true);
      rdbNu.setText("NU");
      rdbNu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rdbNuActionPerformed(evt);
         }
      });

      txtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNgaySinhActionPerformed(evt);
         }
      });

      jLabel10.setBackground(new java.awt.Color(184, 152, 96));
      jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel10.setText("NGAY SINH");

      txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtHoTen.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtHoTenActionPerformed(evt);
         }
      });

      jLabel8.setBackground(new java.awt.Color(184, 152, 96));
      jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel8.setText("HO TEN");

      txtMaDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaDocGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaDocGiaActionPerformed(evt);
         }
      });

      jLabel6.setBackground(new java.awt.Color(184, 152, 96));
      jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel6.setText("MA DOC GIA");

      jLabel16.setBackground(new java.awt.Color(184, 152, 96));
      jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel16.setText("DIA CHI");

      txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtDiaChiActionPerformed(evt);
         }
      });

      txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtEmail.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtEmailActionPerformed(evt);
         }
      });

      jLabel14.setBackground(new java.awt.Color(184, 152, 96));
      jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel14.setText("EMAIL");

      jLabel13.setBackground(new java.awt.Color(184, 152, 96));
      jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel13.setText("SDT");

      txtSdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtSdt.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtSdtActionPerformed(evt);
         }
      });

      btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
      btnThem.setText("THEM");
      btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnThem.setIconTextGap(20);
      btnThem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThemActionPerformed(evt);
         }
      });

      btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
      btnSua.setText("SUA");
      btnSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnSua.setIconTextGap(20);
      btnSua.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSuaActionPerformed(evt);
         }
      });

      btnLuu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
      btnLuu.setText("LUU");
      btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnLuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnLuu.setIconTextGap(20);
      btnLuu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLuuActionPerformed(evt);
         }
      });

      btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove (1).png"))); // NOI18N
      btnXoa.setText("XOA");
      btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnXoa.setIconTextGap(20);
      btnXoa.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaActionPerformed(evt);
         }
      });

      btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searching.png"))); // NOI18N
      btnTimKiem.setText("TIM KIEM");
      btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnTimKiem.setIconTextGap(20);
      btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTimKiemActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(30, 30, 30)
                     .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(44, 44, 44)
                     .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(45, 45, 45)
                     .addComponent(btnXoa)
                     .addGap(27, 27, 27)
                     .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGap(37, 37, 37)
                           .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGap(47, 47, 47)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGap(33, 33, 33)
                           .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGap(18, 18, 18)
                           .addComponent(rdbNam)
                           .addGap(75, 75, 75)
                           .addComponent(rdbNu))
                        .addGroup(layout.createSequentialGroup()
                           .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGap(97, 97, 97)
                     .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addComponent(jScrollPane1)
               .addComponent(jSeparator5)
               .addComponent(jSeparator2))
            .addContainerGap(72, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel8)
               .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel10)
               .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel16)
                     .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(rdbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(10, 10, 10)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel14)
               .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel13)
               .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(111, 111, 111))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void txtMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDocGiaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaActionPerformed

   private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtHoTenActionPerformed

   private void txtSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSdtActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtSdtActionPerformed

   private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtEmailActionPerformed

   private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtDiaChiActionPerformed

   private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtNgaySinhActionPerformed

   private void rdbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNamActionPerformed
		if(rdbNam.isSelected() == true){
			rdbNu.setSelected(false);
		}else{
			rdbNu.setSelected(true);
		}
   }//GEN-LAST:event_rdbNamActionPerformed

   private void rdbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNuActionPerformed
		if(rdbNu.isSelected() == true){
			rdbNam.setSelected(false);
		}else{
			rdbNam.setSelected(true);
		}
   }//GEN-LAST:event_rdbNuActionPerformed

   private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
		toggleLuu = false;
		JTextField[] listTxt = {
   		txtDiaChi,
   		txtEmail,
   		txtHoTen,
   		txtMaDocGia,
   		txtNgaySinh,
   		txtSdt,
		};
		Bar.resetTxt(listTxt);
		this.setEnable();
   }//GEN-LAST:event_btnThemActionPerformed

   private void tblDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocGiaMouseClicked
		this.setDisable();
		int row = tblDocGia.getSelectedRow();
		if(row >= 0){
			DocGia docGia = dao.findById(tblDocGia.getValueAt(row, 0).toString());
			if(docGia == null){
				System.out.println("hshahah");
			}
			if(docGia != null){
				if(docGia.getGoiTinh() == 1){
					rdbNam.setSelected(true);
					rdbNu.setSelected(false);
				}else{
					rdbNam.setSelected(false);
					rdbNu.setSelected(true);
				}
   			txtDiaChi.setText(docGia.getDiaChi());
   			txtEmail.setText(docGia.getEmail());
   			txtHoTen.setText(docGia.getHoTen());
   			txtMaDocGia.setText(docGia.getMaDocGia());
   			txtNgaySinh.setText(docGia.getNgaySinh().toString());
   			txtSdt.setText(docGia.getSdt());
			}
		}
   }//GEN-LAST:event_tblDocGiaMouseClicked

   private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
		JTextField[] listTxt = {
   		txtDiaChi,
   		txtEmail,
   		txtHoTen,
   		txtMaDocGia,
   		txtNgaySinh,
   		txtSdt,
		};
		for(JTextField i: listTxt){
			if(i.getText().equals("")){
				MessDialog.showErrorDialog(this, "CAN NHAP DAY DU CAC TRUONG!!", "ERROR");
				return;
			}
		}
		String maDocGia = txtMaDocGia.getText();
		String hoTen = txtHoTen.getText();
		Date ngaySinh = Date.valueOf(txtNgaySinh.getText());
		int gioiTinh = 0;
		if(rdbNam.isSelected() == true){
			gioiTinh = 1;
		}
		String sdt = txtSdt.getText();
		String email = txtEmail.getText();
		String diaChi = txtDiaChi.getText();
		DocGia docGia = new DocGia(maDocGia, hoTen, (java.sql.Date) ngaySinh, gioiTinh, sdt, email, diaChi);
		if(toggleLuu == false){
			boolean isInsert = dao.insert(docGia);
			if(isInsert == true){
				MessDialog.showMessDialog(this , "THEM THANH CONG!!", "INFO");
				list = dao.selectAll();
				initTbl(model, tblDocGia, headerTbl, list);
			}else{
				MessDialog.showErrorDialog(this, "THAT BAI!!", "ERROR");
			}
		}else{
			int choose = MessDialog.showComfirmDialog(this, "SUA?", "COMFIRM");
			if(choose == 0){
				boolean isUpdate= dao.update(docGia);
				if(isUpdate == true){
					MessDialog.showMessDialog(this , "SUA THANH CONG!!", "INFO");
					list = dao.selectAll();
					initTbl(model, tblDocGia, headerTbl, list);
				}else{
					MessDialog.showErrorDialog(this, "THAT BAI!!", "ERROR");
				}
			}
		}
		
		
   }//GEN-LAST:event_btnLuuActionPerformed

   private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
		this.setEnable();
		toggleLuu = true;
		txtMaDocGia.setEnabled(false);
   }//GEN-LAST:event_btnSuaActionPerformed

   private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
		String maDocGia = txtMaDocGia.getText();
		if(maDocGia.equals("")){
			MessDialog.showErrorDialog(this, "CAN CHON MA BAN DOC DE XOA", "INFO");
			return;
		}
		int choose = MessDialog.showComfirmDialog(this, "XOA ?", "COMFIRM");
		if(choose == 0){
			boolean isDelete = dao.delete(maDocGia);
			if(isDelete == true){
				list = dao.selectAll();
				initTbl(model, tblDocGia, headerTbl, list);
				MessDialog.showMessDialog(this, "XOA THANH CONG!!!", "INFO");
			}else{
				MessDialog.showErrorDialog(this, "THAT BAI!!!", "ERROR");
			}
		}
   }//GEN-LAST:event_btnXoaActionPerformed

   private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
		String maDocGia = txtMaDocGia.getText();
		if(maDocGia.equals("")){
			MessDialog.showErrorDialog(this, "CAN NHAP MA DOC GIA!!", "ERROR");
			return;
		}
		DocGia docGia = dao.findById(maDocGia);
		if(docGia == null){
			MessDialog.showMessDialog(this, "KHONG TIM THAY DOC GIA!!", "ERROR");
		}else{
				if(docGia.getGoiTinh() == 1){
					rdbNam.setSelected(true);
					rdbNu.setSelected(false);
				}else{
					rdbNam.setSelected(false);
					rdbNu.setSelected(true);
				}
   			txtDiaChi.setText(docGia.getDiaChi());
   			txtEmail.setText(docGia.getEmail());
   			txtHoTen.setText(docGia.getHoTen());
   			txtMaDocGia.setText(docGia.getMaDocGia());
   			txtNgaySinh.setText(docGia.getNgaySinh().toString());
   			txtSdt.setText(docGia.getSdt());
		}
   }//GEN-LAST:event_btnTimKiemActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnLuu;
   private javax.swing.JButton btnSua;
   private javax.swing.JButton btnThem;
   private javax.swing.JButton btnTimKiem;
   private javax.swing.JButton btnXoa;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator5;
   private javax.swing.JRadioButton rdbNam;
   private javax.swing.JRadioButton rdbNu;
   private javax.swing.JTable tblDocGia;
   private javax.swing.JTextField txtDiaChi;
   private javax.swing.JTextField txtEmail;
   private javax.swing.JTextField txtHoTen;
   private javax.swing.JTextField txtMaDocGia;
   private javax.swing.JTextField txtNgaySinh;
   private javax.swing.JTextField txtSdt;
   // End of variables declaration//GEN-END:variables
}
