/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.DanhMucDao;
import controllers.DocGiaDao;
import controllers.SachDao;
import foo.Bar;
import foo.MessDialog;
import foo.Validator;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.DanhMuc;
import models.DocGia;
import models.Sach;

/**
 *
 * @author doquy
 */
public class QuanLiDanhMucPn extends javax.swing.JPanel {

	/**
	 * Creates new form FisrtPn
	 */
	private ArrayList<DanhMuc> danhMucList;
	private String[] headerTbl = {
		"MA DANH MUC",
		"TEN DANH MUC",
	};
	private DefaultTableModel model = new DefaultTableModel();
	private DanhMucDao danhMucDao = new DanhMucDao();
	public QuanLiDanhMucPn() {
		danhMucList = danhMucDao.selectAll();
		initComponents();
		initTbl(model, tblDanhMuc, headerTbl, danhMucList);
		initDanhMuc(danhMucList);
		btnLuu.setEnabled(false);
	}
	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<DanhMuc> DanhMucList){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		danhMucList.forEach((elmt) -> {
			model.addRow(new Object[]{
				elmt.getMaDanhMuc(),
				elmt.getTenDanhMuc(),
			});
		});
		tbl.setModel(model);
	}
	private void initDanhMuc(ArrayList<DanhMuc> danhMucList){
		danhMucList.forEach((elmt) -> {
			cbMaDanhMuc.addItem(elmt.getMaDanhMuc());
		});
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator2 = new javax.swing.JSeparator();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblDanhMuc = new javax.swing.JTable();
      cbMaDanhMuc = new javax.swing.JComboBox<>();
      jLabel10 = new javax.swing.JLabel();
      txtTenDanhMuc = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      txtMaDanhMuc = new javax.swing.JTextField();
      btnThem = new javax.swing.JButton();
      btnSua = new javax.swing.JButton();
      btnLuu = new javax.swing.JButton();
      btnXoa = new javax.swing.JButton();
      jSeparator5 = new javax.swing.JSeparator();

      setBackground(new java.awt.Color(255, 255, 204));

      tblDanhMuc.setAutoCreateRowSorter(true);
      tblDanhMuc.setBackground(new java.awt.Color(255, 255, 204));
      tblDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblDanhMuc.setAlignmentX(1.0F);
      tblDanhMuc.setAlignmentY(1.0F);
      tblDanhMuc.setRowHeight(30);
      tblDanhMuc.setRowMargin(3);
      tblDanhMuc.setShowGrid(true);
      tblDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblDanhMucMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblDanhMuc);

      cbMaDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      cbMaDanhMuc.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbMaDanhMucActionPerformed(evt);
         }
      });

      jLabel10.setBackground(new java.awt.Color(184, 152, 96));
      jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel10.setText("MA DANH MUC");

      txtTenDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtTenDanhMuc.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTenDanhMucActionPerformed(evt);
         }
      });

      jLabel8.setBackground(new java.awt.Color(184, 152, 96));
      jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel8.setText("TEN DANH MUC");

      jLabel6.setBackground(new java.awt.Color(184, 152, 96));
      jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel6.setText("MA DANH MUC");

      txtMaDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaDanhMuc.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaDanhMucActionPerformed(evt);
         }
      });

      btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
      btnThem.setText("THEM");
      btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnThem.setIconTextGap(20);
      btnThem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThemActionPerformed(evt);
         }
      });

      btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
      btnSua.setText("SUA");
      btnSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnSua.setIconTextGap(20);
      btnSua.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSuaActionPerformed(evt);
         }
      });

      btnLuu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
      btnLuu.setText("LUU");
      btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnLuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnLuu.setIconTextGap(20);
      btnLuu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLuuActionPerformed(evt);
         }
      });

      btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove (1).png"))); // NOI18N
      btnXoa.setText("XOA");
      btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnXoa.setIconTextGap(20);
      btnXoa.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(51, 51, 51)
                  .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(86, 86, 86)
                  .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(26, 26, 26)
                  .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cbMaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jScrollPane1))))
            .addContainerGap(121, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cbMaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtMaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(58, 58, 58)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnSua)
                  .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(btnXoa)))
            .addGap(18, 18, 18)
            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(316, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
		btnLuu.setEnabled(true);
		JTextField[] listTxt = {
   		txtMaDanhMuc,
   		txtTenDanhMuc,
		};
		Bar.resetTxt(listTxt);
		initTbl(model, tblDanhMuc, headerTbl, danhMucList);
   }//GEN-LAST:event_btnThemActionPerformed

   private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
		JTextField[] listTxt = {
   		txtTenDanhMuc,
   		txtMaDanhMuc,
		};
		boolean bl = true;
		for(JTextField i: listTxt){
			if(i.getText().equals("")){
				MessDialog.showErrorDialog(this, "CAN NHAP DAY DU CAC TRUONG!!", "ERROR");
				return;
			}
		}
		String maDanhMuc = txtMaDanhMuc.getText();
		String tenDanhMuc = txtTenDanhMuc.getText();
		DanhMuc danhMuc = new DanhMuc(maDanhMuc, tenDanhMuc);
		boolean isInsert = danhMucDao.insert(danhMuc);
		if(isInsert == true){
			MessDialog.showMessDialog(this , "THEM THANH CONG!!", "INFO");
			danhMucList = danhMucDao.selectAll();
			initTbl(model, tblDanhMuc, headerTbl, danhMucList);
		}else{
			MessDialog.showErrorDialog(this, "THAT BAI!!", "ERROR");
		}
   }//GEN-LAST:event_btnLuuActionPerformed

   private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
		JTextField[] listTxt = {
   		txtTenDanhMuc,
   		txtMaDanhMuc,
		};
		for(JTextField i: listTxt){
			if(i.getText().equals("")){
				MessDialog.showErrorDialog(this, "CAN NHAP DAY DU CAC TRUONG!!", "ERROR");
				return;
			}
		}
		String maDanhMuc = txtMaDanhMuc.getText();
		String tenDanhMuc = txtTenDanhMuc.getText();
		DanhMuc danhMuc = new DanhMuc(maDanhMuc, tenDanhMuc);
		int choose = MessDialog.showComfirmDialog(this, "SUA?", "COMFIRM");
		if(choose == 0){
			boolean isUpdate= danhMucDao.update(danhMuc);
			if(isUpdate == true){
				MessDialog.showMessDialog(this , "SUA THANH CONG!!", "INFO");
				danhMucList = danhMucDao.selectAll();
				initTbl(model, tblDanhMuc, headerTbl, danhMucList);
			}else{
				MessDialog.showErrorDialog(this, "THAT BAI!!", "ERROR");
			}
		}
		
   }//GEN-LAST:event_btnSuaActionPerformed

   private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
		String maDanhMuc = txtMaDanhMuc.getText();
		if(maDanhMuc.equals("")){
			MessDialog.showErrorDialog(this, "CAN CHON MA BAN DOC DE XOA", "INFO");
			return;
		}
		int choose = MessDialog.showComfirmDialog(this, "XOA ?", "COMFIRM");
		if(choose == 0){
			boolean isDelete = danhMucDao.delete(maDanhMuc);
			if(isDelete == true){
				danhMucList = danhMucDao.selectAll();
				initTbl(model, tblDanhMuc, headerTbl, danhMucList);
				MessDialog.showMessDialog(this, "XOA THANH CONG!!!", "INFO");
			}else{
				MessDialog.showErrorDialog(this, "THAT BAI!!!", "ERROR");
			}
		}
   }//GEN-LAST:event_btnXoaActionPerformed

   private void cbMaDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaDanhMucActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_cbMaDanhMucActionPerformed

   private void txtTenDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDanhMucActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtTenDanhMucActionPerformed

   private void txtMaDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDanhMucActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDanhMucActionPerformed

   private void tblDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhMucMouseClicked
      int row = tblDanhMuc.getSelectedRow();
      if(row >= 0){
         DanhMuc danhMuc = danhMucDao.findById(tblDanhMuc.getValueAt(row, 0).toString());
         if(danhMuc == null){
            System.out.println("hshahah");
         }
         if(danhMuc != null){
            txtMaDanhMuc.setText(danhMuc.getMaDanhMuc());
            txtTenDanhMuc.setText(danhMuc.getTenDanhMuc());
         }
      }
   }//GEN-LAST:event_tblDanhMucMouseClicked


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnLuu;
   private javax.swing.JButton btnSua;
   private javax.swing.JButton btnThem;
   private javax.swing.JButton btnXoa;
   private javax.swing.JComboBox<String> cbMaDanhMuc;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator5;
   private javax.swing.JTable tblDanhMuc;
   private javax.swing.JTextField txtMaDanhMuc;
   private javax.swing.JTextField txtTenDanhMuc;
   // End of variables declaration//GEN-END:variables
}
