/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.DanhMucDao;
import controllers.DocGiaDao;
import controllers.SachDao;
import foo.Bar;
import foo.MessDialog;
import foo.Validator;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.DanhMuc;
import models.DocGia;
import models.Sach;

/**
 *
 * @author doquy
 */
public class QuanLiSachPn extends javax.swing.JPanel {

	/**
	 * Creates new form FisrtPn
	 */
	private ArrayList<Sach> list;
	private ArrayList<DanhMuc> danhMucList;
	private String[] headerTbl = {
		"MA SACH",
		"NXB",
		"MA DANH MUC",
		"TEN SACH",
		"TAC GIA",
		"SO LUONG",
		"NOI DUNG TOM TAT",
	};
	private DefaultTableModel model = new DefaultTableModel();
	private SachDao dao = new SachDao();
	private DanhMucDao danhMucDao = new DanhMucDao();
	private boolean toggleLuu = false;
	public QuanLiSachPn() {
		list = new ArrayList<>();
		list = dao.selectAll();
		danhMucList = danhMucDao.selectAll();
		initComponents();
		initTbl(model, tblSach, headerTbl, list);
		initDanhMuc(danhMucList);
		this.setDisable();
	}
	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<Sach> list){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		list.forEach((elmt) -> {
			model.addRow(new Object[]{
				elmt.getMaSach(),
				elmt.getNxb(),
				elmt.getMaDanhMuc(),
				elmt.getTenSach(),
				elmt.getTacGia(),
				elmt.getSoluong(),
				elmt.getNdTomTat(),
			});
		});
		tbl.setModel(model);
	}
	public void setEnable(){
		txtMaSach.setEnabled(true);
		txtNxb.setEnabled(true);
		cbMaDanhMuc.setEnabled(true);
		txtTenSach.setEnabled(true);
		txtTacGia.setEnabled(true);
		spnSoLuong.setEnabled(true);
		txtNdTomTat.setEnabled(true);
	}
	public void setDisable(){
		txtMaSach.setEnabled(true);
		txtNxb.setEnabled(false);
		cbMaDanhMuc.setEnabled(false);
		txtTenSach.setEnabled(false);
		txtTacGia.setEnabled(false);
		spnSoLuong.setEnabled(false);
		txtNdTomTat.setEnabled(false);
	}
	private void initDanhMuc(ArrayList<DanhMuc> danhMucList){
		danhMucList.forEach((elmt) -> {
			cbMaDanhMuc.addItem(elmt.getMaDanhMuc());
		});
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator2 = new javax.swing.JSeparator();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblSach = new javax.swing.JTable();
      jLabel10 = new javax.swing.JLabel();
      cbMaDanhMuc = new javax.swing.JComboBox<>();
      jLabel9 = new javax.swing.JLabel();
      spnSoLuong = new javax.swing.JSpinner();
      txtNxb = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      txtMaSach = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      jLabel16 = new javax.swing.JLabel();
      jScrollPane2 = new javax.swing.JScrollPane();
      txtNdTomTat = new javax.swing.JTextArea();
      jLabel14 = new javax.swing.JLabel();
      txtTacGia = new javax.swing.JTextField();
      jLabel13 = new javax.swing.JLabel();
      txtTenSach = new javax.swing.JTextField();
      btnThem = new javax.swing.JButton();
      btnSua = new javax.swing.JButton();
      btnLuu = new javax.swing.JButton();
      btnXoa = new javax.swing.JButton();
      btnTimKiem = new javax.swing.JButton();
      jSeparator3 = new javax.swing.JSeparator();

      setBackground(new java.awt.Color(255, 255, 204));

      tblSach.setAutoCreateRowSorter(true);
      tblSach.setBackground(new java.awt.Color(255, 255, 204));
      tblSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblSach.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblSach.setAlignmentX(1.0F);
      tblSach.setAlignmentY(1.0F);
      tblSach.setRowHeight(30);
      tblSach.setRowMargin(3);
      tblSach.setShowGrid(true);
      tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblSachMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblSach);

      jLabel10.setBackground(new java.awt.Color(184, 152, 96));
      jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel10.setText("DANH MUC");

      cbMaDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      cbMaDanhMuc.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbMaDanhMucActionPerformed(evt);
         }
      });

      jLabel9.setBackground(new java.awt.Color(184, 152, 96));
      jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel9.setText("SO LUONG");

      spnSoLuong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

      txtNxb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtNxb.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNxbActionPerformed(evt);
         }
      });

      jLabel8.setBackground(new java.awt.Color(184, 152, 96));
      jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel8.setText("NXB");

      txtMaSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaSach.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaSachActionPerformed(evt);
         }
      });

      jLabel6.setBackground(new java.awt.Color(184, 152, 96));
      jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel6.setText("MA SACH");

      jLabel16.setBackground(new java.awt.Color(184, 152, 96));
      jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel16.setText("NOI DUNG TT");

      txtNdTomTat.setColumns(20);
      txtNdTomTat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtNdTomTat.setRows(5);
      jScrollPane2.setViewportView(txtNdTomTat);

      jLabel14.setBackground(new java.awt.Color(184, 152, 96));
      jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel14.setText("TAC GIA");

      txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtTacGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTacGiaActionPerformed(evt);
         }
      });

      jLabel13.setBackground(new java.awt.Color(184, 152, 96));
      jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel13.setText("TEN SACH");

      txtTenSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtTenSach.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTenSachActionPerformed(evt);
         }
      });

      btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
      btnThem.setText("THEM");
      btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnThem.setIconTextGap(20);
      btnThem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThemActionPerformed(evt);
         }
      });

      btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sua.png"))); // NOI18N
      btnSua.setText("SUA");
      btnSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnSua.setIconTextGap(20);
      btnSua.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSuaActionPerformed(evt);
         }
      });

      btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luu.png"))); // NOI18N
      btnLuu.setText("LUU");
      btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnLuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnLuu.setIconTextGap(20);
      btnLuu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLuuActionPerformed(evt);
         }
      });

      btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove (1).png"))); // NOI18N
      btnXoa.setText("XOA");
      btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnXoa.setIconTextGap(20);
      btnXoa.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaActionPerformed(evt);
         }
      });

      btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searching.png"))); // NOI18N
      btnTimKiem.setText("TIM KIEM");
      btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnTimKiem.setIconTextGap(20);
      btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTimKiemActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(txtNxb, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                           .addComponent(txtMaSach)))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMaDanhMuc, 0, 213, Short.MAX_VALUE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTacGia)))
                              .addGap(29, 29, 29)
                              .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                     .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnLuu)
                        .addGap(30, 30, 30)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(54, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel6)
                     .addComponent(jLabel13)
                     .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNxb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(cbMaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(43, 43, 43)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(67, 67, 67)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(134, 134, 134))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtTenSachActionPerformed

   private void txtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtTacGiaActionPerformed

   private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
		btnLuu.setEnabled(true);
		toggleLuu = false;
		JTextField[] listTxt = {
   		txtMaSach,
   		txtNxb,
   		txtTacGia,
   		txtTenSach,
		};
		Bar.resetTxt(listTxt);
		txtNdTomTat.setText("");
		this.setEnable();
   }//GEN-LAST:event_btnThemActionPerformed

   private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
		this.setDisable();
		int row = tblSach.getSelectedRow();
		if(row >= 0){
			Sach sach = dao.findById(tblSach.getValueAt(row, 0).toString());
			if(sach == null){
				System.out.println("hshahah");
			}
			if(sach != null){
   			txtMaSach.setText(sach.getMaSach());
   			txtTacGia.setText(sach.getTacGia());
   			txtNxb.setText(sach.getNxb());
				txtTenSach.setText(sach.getTenSach());
   			txtNdTomTat.setText(sach.getNdTomTat());
				spnSoLuong.setValue(sach.getSoluong());
			}
		}
   }//GEN-LAST:event_tblSachMouseClicked

   private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
		JTextField[] listTxt = {
   		txtTacGia,
   		txtNxb,
   		txtMaSach,
   		txtTenSach,
		};
		boolean bl = true;
		for(JTextField i: listTxt){
			if(i.getText().equals("")){
				MessDialog.showErrorDialog(this, "CAN NHAP DAY DU CAC TRUONG!!", "ERROR");
				return;
			}
		}
		String maSach = txtMaSach.getText();
		String nxb = txtNxb.getText();
		String maDanhMuc = cbMaDanhMuc.getItemAt(cbMaDanhMuc.getSelectedIndex());
		String tenSach = txtTenSach.getText();
		String tacGia = txtTacGia.getText();
		int soLuong = (int) spnSoLuong.getValue();
		String ndTomTat = txtNdTomTat.getText();
		Sach sach = new Sach(maSach, nxb, maDanhMuc, tenSach, tacGia, soLuong, ndTomTat);
		if(toggleLuu == false){
			boolean isInsert = dao.insert(sach);
			if(isInsert == true){
				MessDialog.showMessDialog(this , "THEM THANH CONG!!", "INFO");
				list = dao.selectAll();
				initTbl(model, tblSach, headerTbl, list);
				this.setDisable();
			}else{
				MessDialog.showErrorDialog(this, "THEM THAT BAI!!", "ERROR");
			}
		}else{
			int choose = MessDialog.showComfirmDialog(this, "SUA?", "COMFIRM");
			if(choose == 0){
				boolean isUpdate= dao.update(sach);
				if(isUpdate == true){
					MessDialog.showMessDialog(this , "SUA THANH CONG!!", "INFO");
					list = dao.selectAll();
					initTbl(model, tblSach, headerTbl, list);
					this.setDisable();
				}else{
					MessDialog.showErrorDialog(this, "SUA THAT BAI!!", "ERROR");
				}
			}
		}
		
   }//GEN-LAST:event_btnLuuActionPerformed

   private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
		this.setEnable();
		txtMaSach.setEnabled(false);
		toggleLuu = true;
   }//GEN-LAST:event_btnSuaActionPerformed

   private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
		String maDocGia = txtMaSach.getText();
		if(maDocGia.equals("")){
			MessDialog.showErrorDialog(this, "CAN CHON MA SACH DE XOA", "ERROR");
			return;
		}
		int choose = MessDialog.showComfirmDialog(this, "XOA ?", "COMFIRM");
		if(choose == 0){
			boolean isDelete = dao.delete(maDocGia);
			if(isDelete == true){
				list = dao.selectAll();
				initTbl(model, tblSach, headerTbl, list);
				MessDialog.showMessDialog(this, "XOA THANH CONG!!!", "INFO");
			}else{
				MessDialog.showErrorDialog(this, "THAT BAI!!!", "ERROR");
			}
		}
   }//GEN-LAST:event_btnXoaActionPerformed

   private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
		String maSach = txtMaSach.getText();
		if(maSach.equals("")){
			MessDialog.showErrorDialog(this, "CAN NHAP MA DOC GIA!!", "ERROR");
			return;
		}
		Sach sach = dao.findById(maSach);
		if(sach == null){
			MessDialog.showMessDialog(this, "KHONG TIM THAY SACH!!", "ERROR");
		}else{
   			txtMaSach.setText(sach.getMaSach());
   			txtTacGia.setText(sach.getTacGia());
   			txtNxb.setText(sach.getNxb());
				txtTenSach.setText(sach.getTenSach());
   			txtNdTomTat.setText(sach.getNdTomTat());
				spnSoLuong.setValue(sach.getSoluong());
		}
   }//GEN-LAST:event_btnTimKiemActionPerformed

   private void cbMaDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaDanhMucActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_cbMaDanhMucActionPerformed

   private void txtNxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNxbActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtNxbActionPerformed

   private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaSachActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnLuu;
   private javax.swing.JButton btnSua;
   private javax.swing.JButton btnThem;
   private javax.swing.JButton btnTimKiem;
   private javax.swing.JButton btnXoa;
   private javax.swing.JComboBox<String> cbMaDanhMuc;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSpinner spnSoLuong;
   private javax.swing.JTable tblSach;
   private javax.swing.JTextField txtMaSach;
   private javax.swing.JTextArea txtNdTomTat;
   private javax.swing.JTextField txtNxb;
   private javax.swing.JTextField txtTacGia;
   private javax.swing.JTextField txtTenSach;
   // End of variables declaration//GEN-END:variables
}
