/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.DocGiaDao;
import controllers.MuonTraDao;
import foo.Bar;
import foo.MessDialog;
import foo.Validator;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.DocGia;
import models.MuonTra;

/**
 *
 * @author doquy
 */
public class ThongKeDocGiaPn extends javax.swing.JPanel {

	/**
	 * Creates new form FisrtPn
	 */
	private ArrayList<DocGia> list;
	private String[] headerTbl = {
		"MA DOC GIA",
		"HO TEN",
	};
	private DefaultTableModel model = new DefaultTableModel();
	private DocGiaDao dao = new DocGiaDao();
	private MuonTraDao muonTraDao = new MuonTraDao();
	private boolean  toggleLuu = false;
	public ThongKeDocGiaPn() {
		list = new ArrayList<>();
		list = dao.selectAll();
		initComponents();
		initTbl(model, tblDocGia, headerTbl, list);
	}
	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<DocGia> list){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		list.forEach((elmt) -> {
			String gioiTinh = "Nam";
			if(elmt.getGoiTinh() == 0){
				gioiTinh = "nu";
			}
			model.addRow(new Object[]{
				elmt.getMaDocGia(),
				elmt.getHoTen(),
				elmt.getNgaySinh(),
				gioiTinh,
				elmt.getEmail(),
				elmt.getDiaChi(),
			});
		});
		tbl.setModel(model);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator1 = new javax.swing.JSeparator();
      jSeparator2 = new javax.swing.JSeparator();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblDocGia = new javax.swing.JTable();
      jPanel4 = new javax.swing.JPanel();
      jSeparator4 = new javax.swing.JSeparator();
      lbHoTen = new javax.swing.JLabel();
      lbGioiTinh = new javax.swing.JLabel();
      lbMaDocGia = new javax.swing.JLabel();
      lbNgaySinh = new javax.swing.JLabel();
      lbSdt = new javax.swing.JLabel();
      lbEmail = new javax.swing.JLabel();
      lbDiaChi = new javax.swing.JLabel();
      jPanel3 = new javax.swing.JPanel();
      jPanel7 = new javax.swing.JPanel();
      jLabel9 = new javax.swing.JLabel();
      cbLuaChon = new javax.swing.JComboBox<>();
      lbKetQua = new javax.swing.JLabel();

      jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

      tblDocGia.setAutoCreateRowSorter(true);
      tblDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblDocGia.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblDocGia.setAlignmentX(1.0F);
      tblDocGia.setAlignmentY(1.0F);
      tblDocGia.setMinimumSize(new java.awt.Dimension(5, 5));
      tblDocGia.setRowHeight(30);
      tblDocGia.setRowMargin(2);
      tblDocGia.setShowGrid(true);
      tblDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblDocGiaMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblDocGia);

      lbHoTen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbMaDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbSdt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbDiaChi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jSeparator4)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lbGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbMaDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
               .addComponent(lbHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbSdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(lbNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap()))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(lbMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(68, 68, 68)
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(383, Short.MAX_VALUE))
         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
               .addGap(141, 141, 141)
               .addComponent(lbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(614, Short.MAX_VALUE)))
      );

      jLabel9.setBackground(new java.awt.Color(184, 152, 96));
      jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel9.setText("LUA CHON:");

      cbLuaChon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      cbLuaChon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thong ke ban doc chua tra sach", "Thong ke ban doc muon sach qua han" }));
      cbLuaChon.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbLuaChonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
      jPanel7.setLayout(jPanel7Layout);
      jPanel7Layout.setHorizontalGroup(
         jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel7Layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(cbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel7Layout.setVerticalGroup(
         jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel7Layout.createSequentialGroup()
            .addComponent(cbLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
         .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      lbKetQua.setBackground(new java.awt.Color(184, 152, 96));
      lbKetQua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      lbKetQua.setText("KET QUA:");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(150, 150, 150)
            .addComponent(lbKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(lbKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(25, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jScrollPane1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jSeparator1)
         .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(32, 32, 32)
                  .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(28, 28, 28)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(90, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void tblDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocGiaMouseClicked
		int row = tblDocGia.getSelectedRow();
		if(row >= 0){
			DocGia docGia = dao.findById(tblDocGia.getValueAt(row, 0).toString());
			if(docGia == null){
				System.out.println("hshahah");
			}
			if(docGia != null){
				if(docGia.getGoiTinh() == 1){
					lbGioiTinh.setText("GIOI TINH: NAM");
				}else{
					lbGioiTinh.setText("GIOI TINH: NAM");
				}
   			lbDiaChi.setText("DIA CHI: \t\t"+ docGia.getDiaChi());
   			lbEmail.setText("EMAIL: \t\t"+docGia.getEmail());
   			lbHoTen.setText("HO TEN: \t\t" + docGia.getHoTen());
   			lbMaDocGia.setText("MA DOC GIA: \t\t" + docGia.getMaDocGia());
   			lbNgaySinh.setText("NGAY SINH: \t\t" + docGia.getNgaySinh().toString());
   			lbSdt.setText("SDT: " + docGia.getSdt());
			}
		}
   }//GEN-LAST:event_tblDocGiaMouseClicked

   private void cbLuaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLuaChonActionPerformed
		int luaChon = cbLuaChon.getSelectedIndex();
		ArrayList<MuonTra> listMuonTra = new ArrayList<>();
		ArrayList<DocGia> listDocGia = new ArrayList<>();
		if(luaChon == 0){
			listMuonTra = muonTraDao.chuaTraList();
			if(listMuonTra != null){
				listMuonTra.forEach((elmt)->{
					DocGia docGia = dao.findById(elmt.getMaDocGia());
					listDocGia.add(docGia);
				});
			}
			if(listDocGia == null){
				lbKetQua.setText("KET QUA: 0");
			}else{
				lbKetQua.setText("KET QUA: " + listDocGia.size());
			}
			initTbl(model, tblDocGia, headerTbl, listDocGia);
			return;
		}
		if(luaChon == 1){
			listMuonTra = muonTraDao.quaHanList();
			if(listMuonTra != null){
				listMuonTra.forEach((elmt)->{
					DocGia docGia = dao.findById(elmt.getMaDocGia());
					listDocGia.add(docGia);
				});
			}
			if(listDocGia == null){
				lbKetQua.setText("KET QUA: 0");
			}else{
				lbKetQua.setText("KET QUA: " + listDocGia.size());
			}
			initTbl(model, tblDocGia, headerTbl, listDocGia);
		}
   }//GEN-LAST:event_cbLuaChonActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<String> cbLuaChon;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel7;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator4;
   private javax.swing.JLabel lbDiaChi;
   private javax.swing.JLabel lbEmail;
   private javax.swing.JLabel lbGioiTinh;
   private javax.swing.JLabel lbHoTen;
   private javax.swing.JLabel lbKetQua;
   private javax.swing.JLabel lbMaDocGia;
   private javax.swing.JLabel lbNgaySinh;
   private javax.swing.JLabel lbSdt;
   private javax.swing.JTable tblDocGia;
   // End of variables declaration//GEN-END:variables
}
