/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.DanhMucDao;
import controllers.DocGiaDao;
import controllers.MuonTraDao;
import controllers.SachDao;
import foo.Bar;
import foo.MessDialog;
import foo.Validator;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.DanhMuc;
import models.DocGia;
import models.MuonTra;
import models.Sach;

/**
 *
 * @author doquy
 */
public class TraCuuMuonTraPn extends javax.swing.JPanel {

	/**
	 * Creates new form FisrtPn
	 */
	private ArrayList<MuonTra> list;
	private String[] headerTbl = {
		"MA DOC GIA",
		"MA SACH",
		"MA THU THU",
		"TEN DOC GIA",
		"NGAY MUON",
		"SO NGAY MUON",
		"TINH TRANG",
	};
	private DefaultTableModel model = new DefaultTableModel();
	private MuonTraDao dao = new MuonTraDao();
	private DocGiaDao docGiaDao = new DocGiaDao();
	private SachDao sachDao = new SachDao();
	private boolean toggleLuu = false;
	public TraCuuMuonTraPn() {
		list = new ArrayList<>();
		list = dao.selectAll();
		initComponents();
		initTbl(model, tblSach, headerTbl, list);
	}
	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<MuonTra> list){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		list.forEach((elmt) -> {
			DocGia docGia = docGiaDao.findById(elmt.getMaDocGia());
			String tenDocGia = docGia.getHoTen();
			String tinhTrang = "";
			if(elmt.getNgayThucTra().toString().equals("2000-02-02")){
				Date curDate = new Date(System.currentTimeMillis());
				Date ngayMuon = elmt.getNgayMuon();
				int hash =  (-1)*((ngayMuon.hashCode() - curDate.hashCode())) / (24 * 60 * 60 * 1000);
				System.out.println(hash );
				System.out.println(elmt.getSoNgayMuon());
				if((hash - elmt.getSoNgayMuon()) <= 0){
					tinhTrang = "CHUA TRA";
				}else{
					tinhTrang = "QUA HAN";
				}
			}else{
				tinhTrang = "DA TRA";
			}
			model.addRow(new Object[]{
				elmt.getMaDocGia(),
				elmt.getMaSach(),
				elmt.getMaThuThu(),
				tenDocGia,
				elmt.getNgayMuon(),
				elmt.getSoNgayMuon(),
				tinhTrang,
			});
		});
		tbl.setModel(model);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator1 = new javax.swing.JSeparator();
      jSeparator2 = new javax.swing.JSeparator();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblSach = new javax.swing.JTable();
      jPanel4 = new javax.swing.JPanel();
      lbTenSach = new javax.swing.JLabel();
      lbTenDocGia = new javax.swing.JLabel();
      lbMaSach = new javax.swing.JLabel();
      lbMaDocGia = new javax.swing.JLabel();
      lbNgayMuon = new javax.swing.JLabel();
      lbSoNgayMuon = new javax.swing.JLabel();
      lbNgayThucTra = new javax.swing.JLabel();
      lbTinhTrang = new javax.swing.JLabel();
      lbSoNgayMuon3 = new javax.swing.JLabel();
      lbKetQua = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      txtMaDocGia = new javax.swing.JTextField();
      btnTimKiem = new javax.swing.JButton();
      txtTenDocGia = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();

      setBackground(new java.awt.Color(255, 255, 204));

      jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

      tblSach.setAutoCreateRowSorter(true);
      tblSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblSach.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblSach.setAlignmentX(1.0F);
      tblSach.setAlignmentY(1.0F);
      tblSach.setRowHeight(30);
      tblSach.setRowMargin(3);
      tblSach.setShowGrid(true);
      tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblSachMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblSach);

      lbTenSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbTenDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbMaSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbMaDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbNgayMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbSoNgayMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbNgayThucTra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbTinhTrang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbSoNgayMuon3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lbTenDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
               .addComponent(lbTenSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbSoNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbNgayThucTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbSoNgayMuon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(lbMaDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
               .addContainerGap()))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(lbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(95, 95, 95)
            .addComponent(lbTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbSoNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34)
            .addComponent(lbNgayThucTra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23)
            .addComponent(lbSoNgayMuon3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(87, Short.MAX_VALUE))
         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
               .addGap(141, 141, 141)
               .addComponent(lbMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(460, Short.MAX_VALUE)))
      );

      lbKetQua.setBackground(new java.awt.Color(184, 152, 96));
      lbKetQua.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
      lbKetQua.setText("SO KET QUA TIM KIEM: ");

      jLabel10.setBackground(new java.awt.Color(184, 152, 96));
      jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel10.setText("MA DOC GIA");

      txtMaDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaDocGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaDocGiaActionPerformed(evt);
         }
      });
      txtMaDocGia.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtMaDocGiaKeyPressed(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtMaDocGiaKeyTyped(evt);
         }
      });

      btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searching.png"))); // NOI18N
      btnTimKiem.setText("TIM KIEM");
      btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnTimKiem.setIconTextGap(20);
      btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTimKiemActionPerformed(evt);
         }
      });

      txtTenDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtTenDocGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTenDocGiaActionPerformed(evt);
         }
      });
      txtTenDocGia.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtTenDocGiaKeyPressed(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtTenDocGiaKeyTyped(evt);
         }
      });

      jLabel6.setBackground(new java.awt.Color(184, 152, 96));
      jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
      jLabel6.setText("TEN DOC GIA");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jSeparator2)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(lbKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(80, 80, 80)
                  .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(72, 72, 72))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(26, 26, 26)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addGroup(layout.createSequentialGroup()
                  .addGap(60, 60, 60)
                  .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(79, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
		int row = tblSach.getSelectedRow();
		if(row >= 0){
			String maDocGia = (String) tblSach.getValueAt(row, 0);
			String maSach = (String) tblSach.getValueAt(row, 1);
			String maThuThu = (String) tblSach.getValueAt(row, 2);
			MuonTra muonTra = dao.findById(maSach, maDocGia);
			if(muonTra == null){
				System.out.println("hshahah");
				return;
			}
			if(muonTra!= null){
				lbMaDocGia.setText("MA DOC GIA: " + muonTra.getMaDocGia());
				lbMaSach.setText("MA SACH: " + muonTra.getMaSach());
				lbMaDocGia.setText("MA DOC GIA: " + muonTra.getMaDocGia());
				lbNgayMuon.setText("NGAY MUON: " + muonTra.getNgayMuon());
				if(muonTra.getNgayThucTra().toString().equals("2000-02-02")){
					lbNgayThucTra.setText("NGAY THUC TRA: " + "null");
				}else{
					lbNgayThucTra.setText("NGAY THUC TRA: " + muonTra.getNgayThucTra());
				}
				lbTinhTrang.setText("TINH TRANG: " + tblSach.getValueAt(row, 6));
				DocGia docGia = docGiaDao.findById(maDocGia);
				lbTenDocGia.setText("TEN DOC GIA: " + docGia.getHoTen());
				Sach sach = sachDao.findById(maSach);
				lbTenSach.setText("TEN SACH: " + sach.getTenSach());
			}
		}
   }//GEN-LAST:event_tblSachMouseClicked

   private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
		String maDocGia = txtMaDocGia.getText();
		ArrayList<MuonTra> listMuonTra = new ArrayList<>();
		listMuonTra = dao.findByIdDocGia(maDocGia);
		if(listMuonTra == null){
			lbKetQua.setText("SO KET QUA TIM KIEM: 0");
		}else{
			lbKetQua.setText("SO KET QUA TIM KIEM: " + listMuonTra.size());
			initTbl(model, tblSach, headerTbl, listMuonTra);
		}
   }//GEN-LAST:event_btnTimKiemActionPerformed

   private void txtTenDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDocGiaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtTenDocGiaActionPerformed

   private void txtTenDocGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDocGiaKeyTyped
		
   }//GEN-LAST:event_txtTenDocGiaKeyTyped

   private void txtTenDocGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDocGiaKeyPressed
		ArrayList<MuonTra> listMuonTra = new ArrayList<>();
		String tenDocGia = txtTenDocGia.getText();
		if(tenDocGia.equals("")){
			lbKetQua.setText("SO KET QUA TIM KIEM: 0");
		}
		ArrayList<DocGia> docGiaList = docGiaDao.findByName(tenDocGia);
		if(docGiaList == null){
			lbKetQua.setText("SO KET QUA TIM KIEM: 0");
		}else{
			docGiaList.forEach((elmt) -> {
				ArrayList<MuonTra> listMuonTra2= dao.findByIdDocGia(elmt.getMaDocGia());
				if(listMuonTra2 != null){
					listMuonTra2.forEach((elmt2)->{
						listMuonTra.add(elmt2);
					});
				}
			});
			lbKetQua.setText("SO KET QUA TIM KIEM: " + listMuonTra.size());
			initTbl(model, tblSach, headerTbl, listMuonTra);
		}
   }//GEN-LAST:event_txtTenDocGiaKeyPressed

   private void txtMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDocGiaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaActionPerformed

   private void txtMaDocGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDocGiaKeyPressed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaKeyPressed

   private void txtMaDocGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDocGiaKeyTyped
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaKeyTyped


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnTimKiem;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JLabel lbKetQua;
   private javax.swing.JLabel lbMaDocGia;
   private javax.swing.JLabel lbMaSach;
   private javax.swing.JLabel lbNgayMuon;
   private javax.swing.JLabel lbNgayThucTra;
   private javax.swing.JLabel lbSoNgayMuon;
   private javax.swing.JLabel lbSoNgayMuon3;
   private javax.swing.JLabel lbTenDocGia;
   private javax.swing.JLabel lbTenSach;
   private javax.swing.JLabel lbTinhTrang;
   private javax.swing.JTable tblSach;
   private javax.swing.JTextField txtMaDocGia;
   private javax.swing.JTextField txtTenDocGia;
   // End of variables declaration//GEN-END:variables
}
