/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.DanhMucDao;
import controllers.DocGiaDao;
import controllers.MuonTraDao;
import controllers.SachDao;
import foo.Bar;
import foo.MessDialog;
import foo.Validator;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.DanhMuc;
import models.DocGia;
import models.MuonTra;
import models.Sach;

/**
 *
 * @author doquy
 */
public class TraCuuMuonTraPn extends javax.swing.JPanel {

	/**
	 * Creates new form FisrtPn
	 */
	private ArrayList<MuonTra> list;
	private String[] headerTbl = {
		"MA DOC GIA",
		"MA SACH",
		"MA THU THU",
		"TEN DOC GIA",
		"NGAY MUON",
		"SO NGAY MUON",
		"TINH TRANG",
	};
	private DefaultTableModel model = new DefaultTableModel();
	private MuonTraDao dao = new MuonTraDao();
	private DocGiaDao docGiaDao = new DocGiaDao();
	private SachDao sachDao = new SachDao();
	private boolean toggleLuu = false;
	public TraCuuMuonTraPn() {
		list = new ArrayList<>();
		list = dao.selectAll();
		initComponents();
		initTbl(model, tblSach, headerTbl, list);
	}
	private void initTbl(DefaultTableModel model , JTable tbl, String[] headerTbl, ArrayList<MuonTra> list){
		model.setRowCount(0);
		model.setColumnIdentifiers(headerTbl);
		list.forEach((elmt) -> {
			DocGia docGia = docGiaDao.findById(elmt.getMaDocGia());
			String tenDocGia = docGia.getHoTen();
			String tinhTrang = "";
			if(elmt.getNgayThucTra().toString().equals("2000-02-02")){
				Date curDate = new Date(System.currentTimeMillis());
				Date ngayMuon = elmt.getNgayMuon();
				int hash = (-1) * (ngayMuon.hashCode() - curDate.hashCode()) / (24 * 60 * 60 * 1000);
				if((hash - elmt.getSoNgayMuon()) <= 0){
					tinhTrang = "CHUA TRA";
				}else{
					tinhTrang = "QUA HAN";
				}
			}else{
				tinhTrang = "DA TRA";
			}
			model.addRow(new Object[]{
				elmt.getMaDocGia(),
				elmt.getMaSach(),
				elmt.getMaThuThu(),
				tenDocGia,
				elmt.getNgayMuon(),
				elmt.getSoNgayMuon(),
				tinhTrang,
			});
		});
		tbl.setModel(model);
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator1 = new javax.swing.JSeparator();
      jSeparator2 = new javax.swing.JSeparator();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblSach = new javax.swing.JTable();
      jPanel3 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jLabel6 = new javax.swing.JLabel();
      txtTenDocGia = new javax.swing.JTextField();
      jPanel9 = new javax.swing.JPanel();
      jLabel10 = new javax.swing.JLabel();
      btnTimKiem = new javax.swing.JButton();
      txtMaDocGia = new javax.swing.JTextField();
      jPanel4 = new javax.swing.JPanel();
      jSeparator4 = new javax.swing.JSeparator();
      lbTenSach = new javax.swing.JLabel();
      lbTenDocGia = new javax.swing.JLabel();
      lbMaSach = new javax.swing.JLabel();
      lbMaDocGia = new javax.swing.JLabel();
      lbNgayMuon = new javax.swing.JLabel();
      lbSoNgayMuon = new javax.swing.JLabel();
      lbNgayThucTra = new javax.swing.JLabel();
      lbTinhTrang = new javax.swing.JLabel();
      lbSoNgayMuon3 = new javax.swing.JLabel();
      lbKetQua = new javax.swing.JLabel();

      jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

      tblSach.setAutoCreateRowSorter(true);
      tblSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      tblSach.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      tblSach.setAlignmentX(1.0F);
      tblSach.setAlignmentY(1.0F);
      tblSach.setRowHeight(30);
      tblSach.setRowMargin(3);
      tblSach.setShowGrid(true);
      tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblSachMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblSach);

      jLabel6.setBackground(new java.awt.Color(184, 152, 96));
      jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel6.setText("TEN DOC GIA");

      txtTenDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtTenDocGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTenDocGiaActionPerformed(evt);
         }
      });
      txtTenDocGia.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtTenDocGiaKeyPressed(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtTenDocGiaKeyTyped(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtTenDocGia))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtTenDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
            .addGap(0, 0, Short.MAX_VALUE))
      );

      jLabel10.setBackground(new java.awt.Color(184, 152, 96));
      jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel10.setText("MA DOC GIA");

      btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searching.png"))); // NOI18N
      btnTimKiem.setText("TIM KIEM");
      btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
      btnTimKiem.setIconTextGap(20);
      btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnTimKiemActionPerformed(evt);
         }
      });

      txtMaDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtMaDocGia.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaDocGiaActionPerformed(evt);
         }
      });
      txtMaDocGia.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtMaDocGiaKeyPressed(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt) {
            txtMaDocGiaKeyTyped(evt);
         }
      });

      javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
      jPanel9.setLayout(jPanel9Layout);
      jPanel9Layout.setHorizontalGroup(
         jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel9Layout.createSequentialGroup()
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
            .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      jPanel9Layout.setVerticalGroup(
         jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel9Layout.createSequentialGroup()
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 7, Short.MAX_VALUE))
         .addGroup(jPanel9Layout.createSequentialGroup()
            .addComponent(txtMaDocGia)
            .addContainerGap())
      );

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(23, Short.MAX_VALUE))
      );

      lbTenSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbTenDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbMaSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbMaDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbNgayMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbSoNgayMuon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbNgayThucTra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbTinhTrang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      lbSoNgayMuon3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jSeparator4)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lbTenDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
               .addComponent(lbTenSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbSoNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbNgayThucTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbSoNgayMuon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(lbMaDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap()))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(lbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(68, 68, 68)
            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lbSoNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34)
            .addComponent(lbNgayThucTra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23)
            .addComponent(lbSoNgayMuon3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
               .addGap(141, 141, 141)
               .addComponent(lbMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap(507, Short.MAX_VALUE)))
      );

      lbKetQua.setBackground(new java.awt.Color(184, 152, 96));
      lbKetQua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      lbKetQua.setText("SO KET QUA TIM KIEM: ");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                     .addGap(158, 158, 158)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(layout.createSequentialGroup()
                     .addContainerGap()
                     .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(40, 40, 40)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(136, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(138, 138, 138))
         .addGroup(layout.createSequentialGroup()
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(127, 127, 127))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
		int row = tblSach.getSelectedRow();
		if(row >= 0){
			String maDocGia = (String) tblSach.getValueAt(row, 0);
			String maSach = (String) tblSach.getValueAt(row, 1);
			String maThuThu = (String) tblSach.getValueAt(row, 2);
			MuonTra muonTra = dao.findById(maSach, maDocGia, maThuThu);
			if(muonTra == null){
				System.out.println("hshahah");
				return;
			}
			if(muonTra!= null){
				lbMaDocGia.setText("MA DOC GIA: " + muonTra.getMaDocGia());
				lbMaSach.setText("MA SACH: " + muonTra.getMaSach());
				lbMaDocGia.setText("MA DOC GIA: " + muonTra.getMaDocGia());
				lbNgayMuon.setText("NGAY MUON: " + muonTra.getNgayMuon());
				if(muonTra.getNgayThucTra().toString().equals("2000-02-02")){
					lbNgayThucTra.setText("NGAY THUC TRA: " + "null");
				}else{
					lbNgayThucTra.setText("NGAY THUC TRA: " + muonTra.getNgayThucTra());
				}
				lbTinhTrang.setText("TINH TRANG: " + tblSach.getValueAt(row, 6));
				DocGia docGia = docGiaDao.findById(maDocGia);
				lbTenDocGia.setText("TEN DOC GIA: " + docGia.getHoTen());
				Sach sach = sachDao.findById(maSach);
				lbTenSach.setText("TEN SACH: " + sach.getTenSach());
			}
		}
   }//GEN-LAST:event_tblSachMouseClicked

   private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
		String maDocGia = txtMaDocGia.getText();
		ArrayList<MuonTra> listMuonTra = new ArrayList<>();
		listMuonTra = dao.findByIdDocGia(maDocGia);
		if(listMuonTra == null){
			lbKetQua.setText("SO KET QUA TIM KIEM: 0");
		}else{
			lbKetQua.setText("SO KET QUA TIM KIEM: " + listMuonTra.size());
			initTbl(model, tblSach, headerTbl, listMuonTra);
		}
   }//GEN-LAST:event_btnTimKiemActionPerformed

   private void txtTenDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDocGiaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtTenDocGiaActionPerformed

   private void txtTenDocGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDocGiaKeyTyped
		
   }//GEN-LAST:event_txtTenDocGiaKeyTyped

   private void txtTenDocGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDocGiaKeyPressed
		ArrayList<MuonTra> listMuonTra = new ArrayList<>();
		String tenDocGia = txtTenDocGia.getText();
		if(tenDocGia.equals("")){
			lbKetQua.setText("SO KET QUA TIM KIEM: 0");
		}
		ArrayList<DocGia> docGiaList = docGiaDao.findByName(tenDocGia);
		if(docGiaList == null){
			lbKetQua.setText("SO KET QUA TIM KIEM: 0");
		}else{
			docGiaList.forEach((elmt) -> {
				ArrayList<MuonTra> listMuonTra2= dao.findByIdDocGia(elmt.getMaDocGia());
				if(listMuonTra2 != null){
					listMuonTra2.forEach((elmt2)->{
						listMuonTra.add(elmt2);
					});
				}
			});
			lbKetQua.setText("SO KET QUA TIM KIEM: " + listMuonTra.size());
			initTbl(model, tblSach, headerTbl, listMuonTra);
		}
   }//GEN-LAST:event_txtTenDocGiaKeyPressed

   private void txtMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDocGiaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaActionPerformed

   private void txtMaDocGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDocGiaKeyPressed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaKeyPressed

   private void txtMaDocGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDocGiaKeyTyped
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMaDocGiaKeyTyped


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnTimKiem;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel9;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator4;
   private javax.swing.JLabel lbKetQua;
   private javax.swing.JLabel lbMaDocGia;
   private javax.swing.JLabel lbMaSach;
   private javax.swing.JLabel lbNgayMuon;
   private javax.swing.JLabel lbNgayThucTra;
   private javax.swing.JLabel lbSoNgayMuon;
   private javax.swing.JLabel lbSoNgayMuon3;
   private javax.swing.JLabel lbTenDocGia;
   private javax.swing.JLabel lbTenSach;
   private javax.swing.JLabel lbTinhTrang;
   private javax.swing.JTable tblSach;
   private javax.swing.JTextField txtMaDocGia;
   private javax.swing.JTextField txtTenDocGia;
   // End of variables declaration//GEN-END:variables
}
